services:
  backend:
    build: ./src
    container_name: file_storage_backend
    command: uvicorn storage.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - db
      - redis
      - minio

  db:
    image: postgres:15
    container_name: file_storage_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: file_storage_redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: file_storage_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

  celery_worker:
    build: ./src
    container_name: file_storage_celery
    command: celery -A storage.services.tasks worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
  minio_data:
